# Generated by Django 4.2.5 on 2023-09-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('experinece', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField()),
                ('study_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studycenter')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('phone_number', models.PositiveIntegerField()),
                ('study_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.studycenter')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
